# Generated by Django 5.2.8 on 2025-12-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=21, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='funcionarios/')),
                ('servicos_especializados', models.ManyToManyField(blank=True, related_name='funcionarios_especialistas', to='servicos.servico')),
            ],
        ),
    ]
