# Generated by Django 5.2.8 on 2025-12-19 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='servicos_especializados',
            new_name='especialidades',
        ),
    ]
