# Generated by Django 5.2.8 on 2025-12-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_initial'),
        ('funcionarios', '0003_alter_funcionario_data_contratacao_and_more'),
    ]

    operations = [
    ]
