# Generated by Django 5.2.8 on 2025-12-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_merge_20251218_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='status',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='telefone',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidade'),
        ),
    ]
