# Generated by Django 5.2.8 on 2025-12-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_horario', models.DateTimeField()),
                ('status', models.CharField(choices=[('AG', 'Agendado'), ('PE', 'Pendente'), ('CA', 'Cancelado'), ('RE', 'Realizado')], default='PE', max_length=2)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['data_horario'],
            },
        ),
    ]
