# Generated by Django 5.2.8 on 2025-12-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_alter_agendamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('AG', 'Agendado'), ('PE', 'Pendente'), ('CA', 'Cancelado'), ('RE', 'Realizado'), ('FA', 'Faltou')], default='AG', max_length=2),
        ),
    ]
