# Generated by Django 5.2.8 on 2025-12-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_initial'),
        ('agendamentos', '0006_alter_agendamento_status'),
    ]

    operations = [
    ]
