# Generated by Django 5.2.8 on 2025-12-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('profissional', 'Profissional')], default='cliente', max_length=15),
        ),
    ]
