# Generated by Django 5.2.8 on 2025-12-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_customuser_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('funcionario', 'Profissional')], default='cliente', max_length=15),
        ),
    ]
