# Generated by Django 5.2.8 on 2025-12-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.RemoveField(
            model_name='servico',
            name='duracao_estimada',
        ),
        migrations.AddField(
            model_name='servico',
            name='duracao',
            field=models.IntegerField(default=30, help_text='Duração do serviço em minutos.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
