# Generated by Django 5.2.8 on 2025-12-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_servico_options_and_more'),
        ('servicos', '0003_alter_servico_options_alter_servico_descricao_and_more'),
    ]

    operations = [
    ]
